export const COLUMN_LABELS: Record<string, string> = {
  // 원자재 (tb_raw_mst)
  raw_code: "원재료 코드",
  raw_name: "원재료명",
  usage_unit: "사용 단위",
  kcal_100g: "열량(100g당, kcal)",
  carb_100g: "탄수화물(100g당, g)",
  protein_100g: "단백질(100g당, g)",
  fat_100g: "지방(100g당, g)",
  kcal_ea: "열량(개당, kcal)",
  carb_ea: "탄수화물(개당, g)",
  protein_ea: "단백질(개당, g)",
  fat_ea: "지방(개당, g)",
  purchase_mode: "구매 방식",
  purchase_section_id: "구매 담당 섹션",
  // 생산품 (tb_prod_mst)
  prod_code: "생산품 코드",
  prod_name: "생산품명",
  avg_daily_usage: "일평균 사용량",
  batch_qty: "배치 수량",
  min_stock_qty: "최소 재고 수량",
  target_stock_qty: "목표 재고 수량",
  container_type: "용기 종류",
  portion_weight: "포션 중량",
  default_sp_entry_stage: "SP 투입 기본 상태",
  // SKU (tb_sku_mst)
  sku_code: "SKU 코드",
  sku_name: "SKU명",
  sku_name_en: "SKU명 (영문)",
  description_en: "설명 (영문)",
  photo_urls: "사진",
  // 공통
  category_code: "카테고리 코드",
  category_name: "카테고리명",
  category_name_kr: "카테고리명 (국문)",
  category_name_en: "카테고리명 (영문)",
  category_type: "카테고리 유형",
  catgegory_id: "카테고리 코드",
  storage: "보관 방식",
  purchase_unit: "구매 단위",
  order_pack_unit: "발주 단위",
  purchase_price: "구매 단가",
  supplier: "거래처",
  shelf_life_days: "보관 기한 (일)",
  std_batch_qty: "표준 배치 수량",
  price: "가격",
  cost: "원가",
  stock: "재고",
  stock_qty: "재고 수량",
  min_stock: "최소 재고",
  status: "상태",
  note: "비고",
  description: "설명",
  name: "이름",
  code: "코드",
  created_by: "생성자",
  updated_by: "수정자",
  barcode: "바코드",
  buy_link: "구매 링크",
  brand: "브랜드",
  sell_price: "판매가",
  concept_tags: "식사 컨셉 태그",
  meal_time_tags: "식사 타이밍 태그",
  diet_tags: "식이 유형 태그",
  nutrition_tags: "영양 태그",
  allergen_tags: "알러지 유발 성분",
  is_active: "활성 여부",
  // 생산 공정 (tb_production_process)
  product_name: "제품명",
  reject_reason: "반려 사유",
  author_id: "작성자 ID",
  approved_by: "승인자 ID",
  step_order: "순서",
  amount_g: "중량(g)",
  // SKU 레시피 (tb_sku_recipe) · 생산품 레시피 (tb_prod_recipe)
  input_id: "레시피 ID",
  sku_id: "SKU",
  prod_id: "생산품",
  raw_id: "원재료",
  ingredient_prod_id: "구성 생산품",
  amount: "수량",
  unit: "단위",
  avg_weight: "평균 무게(g)",
  memo: "메모",
  sort_order: "순서",
  // 포장 부자재 (tb_submat_mst)
  submat_id: "부자재 ID",
  item_name: "품목명",
  item_name_short: "품목명 (축약)",
  manage_part_id: "관리 파트",
  usage_note: "사용 메모",
  qty_per_purchase: "구매당 수량",
  base_unit: "기본 단위",
  purchase_supplier: "구매처",
  purchase_lead_time_day: "구매 리드타임(일)",
  purchase_moq: "최소 구매 수량(MOQ)",
  delivery_note: "배송 메모",
  avg_daily_use_ea: "일평균 사용량(EA)",
  min_stock_ea: "최소 재고(EA)",
  par_stock_ea: "기준 재고(EA)",
  remark: "비고",
  spec: "규격",
  // 매출 주문 (tb_sales_order / tb_sales_order_item)
  platform: "판매 플랫폼",
  order_datetime: "주문 일시",
  total_amount: "총 금액",
  settlement_amount: "정산 금액",
  // 사용자 (users)
  email: "이메일",
  password: "비밀번호",
  role: "역할",
  position: "직책",
  position_id: "직책",
  department: "부서",
  // 직원 (employees)
  store_id: "지점",
  part_id: "파트",
  rank_id: "직급",
  phone: "연락처",
  employment_type: "고용 형태",
  hired_at: "입사일",
  resigned_at: "퇴사일",
  notes: "비고",
  // 지점 (tb_store_mst)
  store_code: "지점 코드",
  store_name: "지점명",
  address: "주소",
  opened_at: "개점일",
  scope: "지점 구분",
  // 구역 (tb_zone_mst)
  zone_type_id: "구역 유형",
  // 방법서 (tb_sop_mst)
  sop_code: "방법서 코드",
  sop_category: "구분",
  sop_title: "제목",
  body: "내용",
  version: "버전",
  target_type: "대상 유형",
  target_id: "대상 ID",
  activated_at: "활성화일",
  // 시설 (tb_asset_mst)
  asset_code: "시설 코드",
  asset_name: "시설명",
  asset_type_id: "시설 유형",
  zone_id: "구역",
  installed_at: "설치일",
  purchase_vendor: "구매처",
  serial_no: "일련번호",
  warranty_until: "보증 만료일",
  as_contact: "A/S 연락처",
  service_vendor: "관리 업체",
}
