export const COLUMN_LABELS: Record<string, string> = {
  // 원자재 (tb_raw_mst)
  raw_code: "원재료 코드",
  raw_name: "원재료명",
  usage_unit: "사용 단위",
  kcal_100g: "열량(100g당, kcal)",
  carb_100g: "탄수화물(100g당, g)",
  protein_100g: "단백질(100g당, g)",
  fat_100g: "지방(100g당, g)",
  kcal_ea: "열량(개당, kcal)",
  carb_ea: "탄수화물(개당, g)",
  protein_ea: "단백질(개당, g)",
  fat_ea: "지방(개당, g)",
  tracking_level: "관리 수준",
  count_size: "규격(개당 g)",
  count_unit: "규격 라벨",
  par_stock: "목표 재고",
  purchase_mode: "구매 방식",
  purchase_section_id: "구매 담당 섹션",
  // 구매 단위(purchase_unit) 하나(예: 1EA, 1박스) 안에 실제로 들어있는 양 — 제품 포장에
  // 적힌 "내용량" 표기와 같은 개념. 예: 구매 단위 EA + 내용량 907 + 내용량 단위 g → 1EA에 907g
  pack_qty: "내용량",
  pack_unit: "내용량 단위",
  origin: "원산지",
  nutrition_source: "영양성분 출처",
  // 생산품 (tb_prod_mst)
  prod_code: "생산품 코드",
  prod_name: "생산품명",
  prod_stage: "생산 단계",
  storage_type: "보관 방식",
  stock_form: "저장 형태",
  unit_size: "규격(내용량)",
  unit_size_uom: "규격 단위",
  default_storage_asset_id: "기본 보관 시설",
  avg_daily_usage: "일평균 사용량",
  batch_qty: "배치 수량",
  min_stock_qty: "최소 재고 수량",
  target_stock_qty: "목표 재고 수량",
  container_type: "용기 종류",
  portion_weight: "포션 중량",
  default_sp_entry_stage: "SP 투입 기본 상태",
  // SKU (tb_sku_mst)
  sku_code: "SKU 코드",
  sku_name: "SKU명",
  sku_name_en: "SKU명 (영문)",
  description_en: "설명 (영문)",
  photo_urls: "사진",
  // 공통
  category_code: "카테고리 코드",
  category_name: "카테고리명",
  category_name_kr: "카테고리명 (국문)",
  category_name_en: "카테고리명 (영문)",
  category_type: "카테고리 유형",
  catgegory_id: "카테고리 코드",
  storage: "보관 방식",
  purchase_unit: "구매 단위",
  supplier: "거래처",
  shelf_life_days: "보관 기한 (일)",
  std_batch_qty: "표준 배치 수량",
  price: "가격",
  cost: "원가",
  stock: "재고",
  min_stock: "최소 재고",
  status: "상태",
  note: "비고",
  description: "설명",
  name: "이름",
  code: "코드",
  created_by: "생성자",
  updated_by: "수정자",
  barcode: "바코드",
  buy_link: "구매 링크",
  brand: "브랜드",
  sell_price: "판매가",
  concept_tags: "식사 컨셉 태그",
  meal_time_tags: "식사 타이밍 태그",
  diet_tags: "식이 유형 태그",
  nutrition_tags: "영양 태그",
  allergen_tags: "알러지 유발 성분",
  is_active: "활성 여부",
  // 생산 공정 (tb_production_process)
  product_name: "제품명",
  reject_reason: "반려 사유",
  author_id: "작성자 ID",
  approved_by: "승인자 ID",
  step_order: "순서",
  amount_g: "중량(g)",
  // SKU 레시피 (tb_sku_recipe) · 생산품 레시피 (tb_prod_recipe)
  input_id: "레시피 ID",
  sku_id: "SKU",
  prod_id: "생산품",
  raw_id: "원재료",
  ingredient_prod_id: "구성 생산품",
  amount: "수량",
  unit: "단위",
  avg_weight: "평균 무게(g)",
  memo: "메모",
  sort_order: "순서",
  // 포장 부자재 (tb_submat_mst)
  submat_id: "부자재 ID",
  item_name: "품목명",
  manage_part_id: "관리 파트",
  usage_note: "사용 메모",
  base_unit: "재고 단위",
  qty_per_pack: "팩당 수량(EA)",
  packs_per_box: "박스당 팩 수",
  min_stock_pack: "최소 재고(팩)",
  par_stock_pack: "적정 재고(팩)",
  remark: "비고",
  spec: "규격",
  // 매출 주문 (tb_sales_order / tb_sales_order_item)
  platform: "판매 플랫폼",
  order_datetime: "주문 일시",
  total_amount: "총 금액",
  settlement_amount: "정산 금액",
  // 사용자 (users)
  email: "이메일",
  password: "비밀번호",
  role: "역할",
  position: "직책",
  position_id: "직책",
  department: "부서",
  // 직원 (staff)
  store_id: "지점",
  part_id: "파트",
  rank_id: "직급",
  phone: "연락처",
  employment_type: "고용 형태",
  hired_at: "입사일",
  resigned_at: "퇴사일",
  notes: "비고",
  // 지점 (tb_store_mst)
  store_code: "지점 코드",
  store_name: "지점명",
  address: "주소",
  opened_at: "개점일",
  scope: "지점 구분",
  // 구역 (tb_zone_mst)
  zone_type_id: "구역 유형",
  // 보관영역 (tb_storage_area_mst)
  area_name: "영역 이름",
  // 방법서 (tb_sop_mst)
  sop_code: "방법서 코드",
  sop_category: "구분",
  sop_title: "제목",
  body: "내용",
  version: "버전",
  target_type: "대상 유형",
  target_id: "대상 ID",
  activated_at: "활성화일",
  // 시설 (tb_asset_mst)
  asset_code: "시설 코드",
  asset_name: "시설명",
  asset_type_id: "시설 유형",
  zone_id: "구역",
  installed_at: "설치일",
  purchase_vendor: "구매처",
  serial_no: "일련번호",
  warranty_until: "보증 만료일",
  as_contact: "A/S 연락처",
  service_vendor: "관리 업체",
  // 감사 로그 (tb_audit_log)
  table_name: "테이블",
  pk_column: "PK 컬럼",
  pk_value: "PK 값",
  action: "동작",
  column_name: "수정된 컬럼",
  old_value: "이전 값",
  new_value: "새 값",
  changed_by_name: "작업자",
  changed_at: "작업 시각",
  changed_by: "작업자 ID",

  // 공통 시스템 필드
  id: "ID",
  created_at: "생성일시",
  updated_at: "수정일시",
  title: "제목",
  content: "내용",
  category: "카테고리",
  level: "레벨",
  name_ko: "이름(국문)",

  // 시설/설비 상세 (tb_asset_type_mst, asset_fn/fc/eq_details 등)
  asset_id: "시설",
  asset_type: "자산 유형",
  asset_type_code: "시설 유형 코드",
  asset_type_name: "시설 유형명",
  facility_category: "시설 분류",
  depth_mm: "깊이(mm)",
  height_mm: "높이(mm)",
  width_mm: "너비(mm)",
  weight_kg: "무게(kg)",
  material: "재질",
  standard_name: "표준명",
  manufacturer: "제조사",
  model_no: "모델번호",
  vendor: "업체",
  utility: "유틸리티",
  requires_temp_check: "온도 점검 필요 여부",
  purchase_date: "구매일",
  construction_date: "준공일",
  inspect_cycle: "점검 주기",
  last_inspected_at: "최근 점검일",
  next_inspect_at: "다음 점검 예정일",
  quantity: "수량",

  // 근태 (tb_sp_attendance_log, tb_sp_staff_auth)
  check_type: "출퇴근 구분",
  checked_at: "출퇴근 시각",
  staff_id: "직원",
  pin_hash: "PIN 해시",

  // 생산 공정 (tb_production_process, tb_production_process_step)
  approved_at: "승인일시",
  process_id: "공정",
  item: "품목",

  // 원재료/생산품 추가
  purchase_price: "구매 단가",
  owner_part: "담당 파트",
  yield_rate: "수율",

  // 매출 주문 (tb_sales_order, tb_sales_order_item)
  commission_amount: "수수료 금액",
  discount_amount: "할인 금액",
  external_order_id: "외부 주문 ID",
  order_number: "주문 번호",
  raw: "원본 데이터",
  order_id: "주문",
  is_canceled: "취소 여부",
  options: "옵션",
  unit_price: "단가",
  subtotal: "소계",

  // 카테고리 부가 정보
  emoji: "이모지",
  category_emoji: "이모지",

  // 보관영역/구역
  area_id: "보관영역",
  zone_function: "구역 기능",
  zone_group: "구역 그룹",
  zone_type_code: "구역 유형 코드",
  zone_type_name: "구역 유형명",

  // 공지
  target_position_id: "대상 직책",
  notice_id: "공지",
  acked_at: "확인일시",

  // 포장 부자재 재고 트랜잭션 (tb_submat_stock_txn)
  input_box: "입고 박스 수",
  input_pack: "입고 팩 수",
  qty: "수량",
  reason_memo: "사유 메모",
  reason_type: "사유 구분",
  txn_id: "거래 ID",
  txn_type: "거래 유형",

  // 원재료·생산품 재고 트랜잭션 (tb_raw_stock_txn / tb_prod_stock_txn)
  input_count: "입력 개수",
  input_g: "입력 무게(g)",
  reason_code: "사유 코드",
  ref_type: "출처 유형",
  ref_id: "출처 ID",
  audit_batch_id: "실사 묶음 ID",

  // 생산 로그 (tb_prod_log)
  log_id: "생산 로그 ID",
  recipe_h_id: "적용 레시피",
  worker_id: "작업자",
  output_qty: "생산 산출량",
  labor_min: "작업 시간(분)",

  // 방법서 상세(sop_steps) · 구 방법서(sop_mst)
  caution: "주의사항",
  instruction: "작업 지시",
  qc_standard: "품질 기준",
  shelf_hours: "보관 가능 시간",
  step_name: "단계명",
  step_no: "단계 번호",
  sop_id: "방법서 ID",
  sop_name: "방법서명",

  // 열 순서/숨김 설정 저장(table_column_prefs)
  column_order: "열 순서",
  hidden_columns: "숨긴 열",

  // 초대/섹션 배정
  invited_at: "초대일시",
  section_id: "섹션",
  assigned_at: "배정일시",
  is_primary: "주 담당 여부",
}
