export const COLUMN_LABELS: Record<string, string> = {
  // 원자재 (tb_raw_mst)
  raw_code: "원자재 코드",
  raw_name: "원자재명",
  // 생산품 (tb_prod_mst)
  prod_code: "생산품 코드",
  prod_name: "생산품명",
  // SKU (tb_sku_mst)
  sku_code: "SKU 코드",
  sku_name: "SKU명",
  sku_name_en: "SKU명 (영문)",
  description_en: "설명 (영문)",
  // 공통
  category_code: "카테고리 코드",
  category_name: "카테고리명",
  catgegory_id: "카테고리 코드",
  storage: "보관 방식",
  purchase_unit: "구매 단위",
  purchase_price: "구매 단가",
  supplier: "거래처",
  shelf_life_days: "보관 기한 (일)",
  price: "가격",
  cost: "원가",
  stock: "재고",
  min_stock: "최소 재고",
  photo: "사진",
  status: "상태",
  note: "비고",
  description: "설명",
  name: "이름",
  code: "코드",
  created_by: "생성자",
  updated_by: "수정자",
  barcode: "바코드",
  buy_link: "구매 링크",
  brand: "브랜드",
  sell_price: "판매가",
  concept_tags: "식사 컨셉 태그",
  meal_time_tags: "식사 타이밍 태그",
  diet_tags: "식이 유형 태그",
  nutrition_tags: "영양 태그",
  allergen_tags: "알러지 유발 성분",
  // 생산 공정 (tb_production_process)
  product_name: "제품명",
  reject_reason: "반려 사유",
  author_id: "작성자 ID",
  approved_by: "승인자 ID",
  step_order: "순서",
  amount_g: "중량(g)",
  // SKU 레시피 (tb_sku_recipe) · 생산품 레시피 (tb_prod_recipe)
  input_id: "레시피 ID",
  sku_id: "SKU",
  prod_id: "생산품",
  raw_id: "원자재",
  amount: "수량",
  unit: "단위",
  memo: "메모",
  sort_order: "순서",
  // 사용자 (users)
  email: "이메일",
  password: "비밀번호",
  role: "역할",
  position: "직책",
  position_id: "직책",
  department: "부서",
  // 직원 (employees)
  store_id: "매장",
  part_id: "파트",
  rank_id: "직급",
  phone: "연락처",
  employment_type: "고용 형태",
  hired_at: "입사일",
  resigned_at: "퇴사일",
  notes: "비고",
}
